
    //     Hotel Booking SystemMain Question: Find most frequently booked room in the last 6 months.Tables:
// Rooms(room_id, type, price)
// Bookings(booking_id, room_id, guest_id, check_in, check_out)
// Guests(guest_id, name)
//  Use Cases:Show number of times each room was booked.
// List rooms never booked in the last 12 months.
// Find average stay duration per guest.
// Get total revenue generated by each room type.
// Show top 3 guests by number of stays.
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;


// Room class
class Room {
    int roomId;
    String type;
    double price;

    Room(int roomId, String type, double price) {
        this.roomId = roomId;
        this.type = type;
        this.price = price;
    }

    public String toString() {
        return "Room{" + roomId + ", " + type + ", " + price + "}";
    }
}

// Guest class
class Guest {
    int guestId;
    String name;

    Guest(int guestId, String name) {
        this.guestId = guestId;
        this.name = name;
    }

    public String toString() {
        return "Guest{" + guestId + ", " + name + "}";
    }
}

// Booking class
class Booking {
    int bookingId;
    Room room;
    Guest guest;
    LocalDate checkIn;
    LocalDate checkOut;

    Booking(int bookingId, Room room, Guest guest, LocalDate checkIn, LocalDate checkOut) {
        this.bookingId = bookingId;
        this.room = room;
        this.guest = guest;
        this.checkIn = checkIn;
        this.checkOut = checkOut;
    }

    long getStayDuration() {
        return ChronoUnit.DAYS.between(checkIn, checkOut);
    }
}


class HotelService {
    Room[] rooms;
    Guest[] guests;
    Booking[] bookings;

    HotelService(Room[] rooms, Guest[] guests, Booking[] bookings) {
        this.rooms = rooms;
        this.guests = guests;
        this.bookings = bookings;
    }

    // 1. Most frequently booked room in last 6 months
    Room getMostBookedRoomLast6Months() {
        LocalDate sixMonthsAgo = LocalDate.now().minusMonths(6);
        int[] count = new int[rooms.length]; // count bookings per room

        for (Booking b : bookings) {
            if (b.checkIn.isAfter(sixMonthsAgo)) {
                for (int i = 0; i < rooms.length; i++) {
                    if (rooms[i] == b.room) {
                        count[i]++;
                    }
                }
            }
        }

        int maxIndex = 0;
        for (int i = 1; i < count.length; i++) {
            if (count[i] > count[maxIndex]) {
                maxIndex = i;
            }
        }
        return rooms[maxIndex];
    }

    // 2. Number of times each room was booked
    void showBookingCountPerRoom() {
        int[] count = new int[rooms.length];

        for (Booking b : bookings) {
            for (int i = 0; i < rooms.length; i++) {
                if (rooms[i] == b.room) {
                    count[i]++;
                }
            }
        }

        for (int i = 0; i < rooms.length; i++) {
            System.out.println(rooms[i].type + " booked " + count[i] + " times");
        }
    }

    // 3. Rooms never booked in last 12 months
    void showUnbookedRoomsLast12Months() {
        LocalDate oneYearAgo = LocalDate.now().minusYears(1);
        boolean[] booked = new boolean[rooms.length];

        for (Booking b : bookings) {
            if (b.checkIn.isAfter(oneYearAgo)) {
                for (int i = 0; i < rooms.length; i++) {
                    if (rooms[i] == b.room) {
                        booked[i] = true;
                    }
                }
            }
        }

        for (int i = 0; i < rooms.length; i++) {
            if (!booked[i]) {
                System.out.println("Room never booked in last 12 months: " + rooms[i].type);
            }
        }
    }

    // 4. Average stay duration per guest
    void showAvgStayDurationPerGuest() {
        long[] totalDays = new long[guests.length];
        int[] stays = new int[guests.length];

        for (Booking b : bookings) {
            for (int i = 0; i < guests.length; i++) {
                if (guests[i] == b.guest) {
                    totalDays[i] += b.getStayDuration();
                    stays[i]++;
                }
            }
        }

        for (int i = 0; i < guests.length; i++) {
            double avg = (stays[i] == 0) ? 0 : (double) totalDays[i] / stays[i];
            System.out.println(guests[i].name + " average stay = " + avg + " days");
        }
    }

    // 5. Total revenue generated by each room type
    void showRevenueByRoomType() {
        double[] revenue = new double[rooms.length];

        for (Booking b : bookings) {
            for (int i = 0; i < rooms.length; i++) {
                if (rooms[i] == b.room) {
                    revenue[i] += b.getStayDuration() * rooms[i].price;
                }
            }
        }

        for (int i = 0; i < rooms.length; i++) {
            System.out.println("Revenue for " + rooms[i].type + " = " + revenue[i]);
        }
    }

    // 6. Top 3 guests by number of stays
    void showTop3GuestsByStays() {
        int[] stays = new int[guests.length];

        for (Booking b : bookings) {
            for (int i = 0; i < guests.length; i++) {
                if (guests[i] == b.guest) {
                    stays[i]++;
                }
            }
        }

        // find top 3 manually
        for (int k = 0; k < 3; k++) {
            int maxIndex = -1;
            for (int i = 0; i < stays.length; i++) {
                if (maxIndex == -1 || stays[i] > stays[maxIndex]) {
                    maxIndex = i;
                }
            }
            if (maxIndex != -1 && stays[maxIndex] > 0) {
                System.out.println("Top Guest #" + (k + 1) + ": " + guests[maxIndex].name + " with " + stays[maxIndex] + " stays");
                stays[maxIndex] = -1; // mark as used
            }
        }
    }
} 
public class HotelSystemArrayDemo {
    public static void main(String[] args) {
        // Create Rooms
        Room r1 = new Room(1, "Deluxe", 2000);
        Room r2 = new Room(2, "Suite", 5000);
        Room r3 = new Room(3, "Standard", 1000);

        Room[] rooms = {r1, r2, r3};

        // Create Guests
        Guest g1 = new Guest(1, "Alice");
        Guest g2 = new Guest(2, "Bob");
        Guest g3 = new Guest(3, "Charlie");

        Guest[] guests = {g1, g2, g3};

        // Create Bookings
        Booking[] bookings = {
            new Booking(101, r1, g1, LocalDate.now().minusMonths(2), LocalDate.now().minusMonths(2).plusDays(3)),
            new Booking(102, r2, g2, LocalDate.now().minusMonths(4), LocalDate.now().minusMonths(4).plusDays(2)),
            new Booking(103, r1, g2, LocalDate.now().minusMonths(5), LocalDate.now().minusMonths(5).plusDays(4)),
            new Booking(104, r3, g3, LocalDate.now().minusMonths(14), LocalDate.now().minusMonths(14).plusDays(1))
        };

        // Create service
        HotelService service = new HotelService(rooms, guests, bookings);

        // Call methods
        System.out.println("Most booked room (last 6 months): " + service.getMostBookedRoomLast6Months().type);
        service.showBookingCountPerRoom();
        service.showUnbookedRoomsLast12Months();
        service.showAvgStayDurationPerGuest();
        service.showRevenueByRoomType();
        service.showTop3GuestsByStays();
    }
}


    
}
